blank_issues_enabled: true
contact_links:
  - name: 💬 Team chat
    url: https://github.com/craigcossairt/hitlab-uvu-world-cup-hackathon-2026/discussions
    about: For quick questions during the hackathon, prefer the team chat over filing an issue.
